version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:stretch

jobs:
  build:
    executor: default
    steps:
      - checkout

      - run:
          name: Show posts that changed
          command: |
            POSTS=$(git diff --name-only --diff-filter=am origin/master)
            echo 'export POSTS="'"$POSTS"'"' >> $BASH_ENV

            echo "The following posts will be published:$POSTS"

  publish_medium_story:
    executor: default
    parameters:
      lang:
        type: enum
        default: en-us
        enum: ["en-us", "pt-br"]
      md_token:
        type: string
      md_user_id:
        type: string

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go get -u github.com/cjoudrey/md2medium

      - run:
          name: Setup config
          command: |
            echo '{"github_access_token":"'"$GH_TOKEN"'",
                  "medium_access_token":"'"$MD_US_TOKEN"'",
                  "medium_user_id":"'"$MD_US_UID"'"}' > "$HOME/.md2medium"

      - run:
          name: Grab posts that changed
          command: |
            POSTS=$(git diff --name-only --diff-filter=am origin/master | grep << parameters.lang >>)
            echo 'export POSTS="'"$POSTS"'"' >> $BASH_ENV

      - run:
          name: Output posts
          command: echo "The following posts will be published:$POSTS"

      - run:
          name: Publish post
          command: |
            if [ -z "$POSTS" ]; then
              echo "No post found to publish"
            else
              md2medium $POSTS
            fi

workflows:
  version: 2

  build_deploy:
    jobs:
      - build

      - publish_medium_approval:
          type: approval
          requires:
            - build

      - publish_medium_story:
          name: publish_medium_story_EN-US
          lang: en-us
          md_token: $MD_US_TOKEN
          md_user_id: $MD_US_UID
          requires:
            - publish_medium_approval

      - publish_medium_story:
          name: publish_medium_story_PT-BR
          lang: pt-br
          md_token: $MD_BR_TOKEN
          md_user_id: $MD_BR_UID
          requires:
            - publish_medium_approval
