version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:stretch

jobs:
  build:
    executor: default
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go get -u github.com/cjoudrey/md2medium

      - run:
          name: Setup config
          command: |
            echo '{"github_access_token":"'"$GH_TOKEN"'",
                  "medium_access_token":"'"$MD_US_TOKEN"'",
                  "medium_user_id":"'"$MD_US_UID"'"}' > "$HOME/.md2medium"

      - run:
          name: Grab posts that changed
          command: |
            POSTS=$(git diff --name-only --diff-filter=am origin/master)
            echo 'export POSTS="'"$POSTS"'"' >> $BASH_ENV

      - run:
          name: Output posts
          command: echo "The following posts will be published:$POSTS"

      - run:
          name: Publish post
          command: md2medium $POSTS

workflows:
  version: 2

  build_deploy:
    jobs:
      - build
